// lang.js - 中英文文案 (zh/en strings) - TC-tools Node.js edition
'use strict';

const S = (n, zh, en) => ({ [n]: { zh, en } })[n];

const ZH = {
  version: '版本 %s',
  osUnsupported: '不支持的系统！需要 Windows 10 1703（build 15063）或更高版本。当前：%s',
  osLine: '系统：%s',
  langLine: '语言：%s（首页可选 4 切换）',
  hintChoose: '请输入选项序号后回车：',
  invalidChoice: '无效选项，请重新输入。',
  pressEnter: '按回车键继续...',
  back: '返回上一页',
  ok: '完成',
  fail: '失败',
  goodbye: '感谢使用 TC-tools，再见！',
  canceled: '已取消。',
  homeIntro: '欢迎使用 TC-tools —— 面向 Windows 10 1709+ 的工具链安装/检查/轻量CLI 工具箱',
  m1: '工具链安装工具包',
  m2: '工具链检查及疑难解答',
  m3: '内置轻量 CLI',
  m4: '切换语言（中文/English）',
  m5: '进入我们的网站',
  m6: '退出',
  langSwitched: '已切换语言：%s',
  webOpened: '已在默认浏览器中打开 https://turtleweb.cc.cd',
  p1Title: '工具链安装工具包',
  p1Local: '本地安装（可能版本较旧，但最快）',
  p1Online: '在线安装（版本最新，快慢取决于网络）',
  commentLocal: '本地安装使用预先打包到 packages 目录的安装包，无需联网即可安装。',
  commentOnline: '在线安装将自动下载最新版安装包，速度取决于网络状况。',
  itNode: '安装 Node.js',
  itMingw: '安装 MinGW-w64',
  itGit: '安装 Git for Windows',
  itMsys2: '安装 MSYS2',
  itPnpm: '安装 pnpm',
  itDsh: '安装 Deepseek Harness',
  itDshNpm: '安装 Deepseek Harness（npm -g 全局安装）',
  itDshNpx: '安装 Deepseek Harness（npx 安装并启动）',
  itDshGit: '安装 Deepseek Harness（git + pnpm 源码安装）',
  itC1: '安装编辑器/IDE套餐一（Bloodshed DEV-C++ 5.11.0 + VS Code）',
  itC2: '安装编辑器/IDE套餐二（PyCharm + IDLE（Python 3）+ Jetbrains Toolbox）',
  itC3: '安装编辑器/IDE套餐三（CLion + MinGW-w64 13.2 + Jetbrains Toolbox）',
  itC4: '安装编辑器/IDE套餐四（Qt online installer）',
  itOffice: '安装办公/教育套餐一（WPS + QQ + 希沃白板 + 钉钉 + 微信）',
  itAi: '安装AI套餐一（codex + claude code）',
  verLabel: '（版本：%s）',
  instAlready: '检测到 %s 已安装（%s），为防止重复安装已跳过。',
  instOsBlock: '安装前检查：当前系统为 %s，不满足 Windows 10 1703（build 15063）及以上要求，已取消安装。',
  instAiBlock: '当前系统为 Windows 10 1709 或更早（build %d），codex/claude code 无法安装（需要 Windows 10 1803+）。',
  instLocalMissing: '未找到本地安装包：%s\n请先在仓库中运行  packages\fetch-packages.ps1  下载离线包，或改用【在线安装】。',
  instDl: '正在下载：%s',
  instDlBad: '下载异常：服务器返回了网页而非安装包（可能被运营商/镜像拦截）。请改用浏览器手动下载。',
  instRunSilent: '正在静默安装，请稍候（如弹出 UAC 请点击【是】）...',
  instRunInter: '正在启动交互式安装程序，安装完成后请回到本窗口按回车继续。',
  instStart: '开始安装：%s',
  instOk: '安装成功！已尝试自动验证。',
  instFail: '安装未成功（退出码 %d）。',
  instCancel: '安装程序未启动或被取消（UAC 拒绝/退出码 %d）。',
  instNodeMissing: '未检测到 Node.js / npm。请先执行：安装 Node.js。',
  instGitMissing: '未检测到 Git。请先执行：安装 Git for Windows。',
  instPathNote: '提示：PATH 修改后请重新打开终端（本程序）使路径生效。',
  instVerifyOk: '验证通过：%s',
  instVerifyFail: '验证未通过：未找到 %s。请排查安装或 PATH 设置。',
  instOfflinePage: '已在浏览器打开官方下载页：%s',
  instQtNote: '提示：Qt 6 系列（6.2+）官方要求 Windows 10 1809+；Win10 1709 请选择 Qt 5.15.x。',
  instJbNote: '提示：JetBrains 2023.2 起官方要求 Windows 10 1809+，在 1709 上可能无法运行，请知悉。',
  comboDone: '套餐安装流程结束。',
  installed: '已安装：%s',
  p2Title: '工具链检查及疑难解答',
  c1: '展示已安装的工具链及版本',
  c2: 'Node.js 运行及依赖检查',
  c3: 'Git 运行检查',
  c4: 'pnpm 运行检查',
  c5: 'MSYS2 运行检查',
  c6: 'Deepseek Harness 运行及依赖检查',
  c7: 'Claude Code 运行检查',
  c8: 'Codex 运行检查',
  c9: 'Microsoft Edge 运行检查',
  c10: 'Google Chrome 运行检查',
  c11: 'DEV-C++ 运行检查',
  c12: 'MinGW-w64 运行检查',
  c13: 'Python 运行检查',
  c14: 'IDE 运行检查（检查已安装的 IDE）',
  c15: '办公软件检查',
  c16: '返回上一页',
  chkHeader: '--- %s ---',
  chkVer: '版本：%s',
  chkPath: '路径：%s',
  chkNotFound: '[X] 未检测到 %s',
  chkOk: '[OK] 运行正常',
  chkError: '[!] 检测到但无法运行：%s',
  chkSummaryHead: '===== 已安装工具链总览 =====',
  chkSummaryTotal: '共 %d 项',
  tipNode: '建议：使用 1-工具链安装工具包 安装 Node.js；或从 https://nodejs.org 安装。',
  tipGit: '建议：使用 1-工具链安装工具包 安装 Git（安装时请勾选【添加到 PATH】）。',
  tipPnpm: '建议：先安装 Node.js，再执行 npm install -g pnpm。',
  tipMsys2: '建议：使用 1-工具链安装工具包 安装 MSYS2；或从 https://www.msys2.org 获取。',
  tipDsh: '建议：使用 1-工具链安装工具包（在线安装 5A/5B/5C）安装 Deepseek Harness。',
  tipClaude: '建议：npm install -g @anthropic-ai/claude-code（需 Node，需 Windows 10 1803+）。',
  tipCodex: '建议：npm install -g @openai/codex（需 Node，需 Windows 10 1803+）。',
  tipEdge: '建议：Windows 10 1709 自带 Edge；可使用 Edge 自动更新获得新版。',
  tipChrome: '建议：从 https://www.google.com/chrome/ 下载安装。',
  tipDevCpp: '建议：使用 1-工具链安装工具包 套餐一安装 DEV-C++ 5.11.0。',
  tipMingw: '建议：使用 1-工具链安装工具包 安装 MinGW-w64 13.2。',
  tipPython: '建议：使用 1-工具链安装工具包 套餐二安装 Python 3（含 IDLE）。',
  tipIde: '提示：IDE 建议包含：VS Code / PyCharm / CLion / JetBrains Toolbox / Qt Creator / DEV-C++。',
  tipOffice: '提示：办公/教育软件：WPS、QQ、希沃白板、钉钉、微信（见套餐一）。',
  p3Title: '内置轻量 CLI',
  p3Desc1: '  - 可在 Windows 10 1709 上运行的轻量命令式 AI 对话工具。',
  p3Desc2: '  - 通过 API Key 连接模型：选择厂商只需填 Key；也可自定义全部参数。',
  p3Desc3: '  - 类 Claude Code 的对话样式；输入 /exit 返回上一页。',
  p3Start: '启动轻量 CLI',
  cliSelVendor: '请选择模型厂商：',
  cliVDeeSeek: 'DeepSeek（仅需 API Key）',
  cliVOpenAI: 'OpenAI',
  cliVMoonshot: 'Moonshot / Kimi',
  cliVGLM: '智谱 GLM',
  cliVQwen: '阿里云百炼 DashScope（兼容模式）',
  cliVSilicon: '硅基流动 SiliconFlow',
  cliVArk: '火山方舟 Volcengine Ark',
  cliVOllama: 'Ollama（本地，无需 API Key）',
  cliVCustom: '自定义（自行填写所有数据）',
  cliKey: '请输入 API Key（输入后回车，回车留空表示无）：',
  cliUrl: '请输入 Base URL（如 https://api.deepseek.com）：',
  cliModel: '请输入模型名称（如 deepseek-chat）：',
  cliSave: '是否保存配置（下次自动载入，Key 会明文保存到 %APPDATA%\\TC-tools\\cli-config.json）？(y/n)：',
  cliSaved: '已保存。',
  cliLoaded: '已载入上次保存的配置。',
  cliHelp: '命令：/exit 返回上一页 | /clear 清空对话 | /help 帮助',
  cliPrompt: '> ',
  cliErrNoKey: '未配置 API Key。请重新启动 CLI 并选择厂商 / 自定义。',
  cliErrHttp: '请求失败：%s',
  cliErrStatus: '服务器返回 HTTP %d：%s',
  cliBye: '已退出 CLI，返回上一页。',
  cliChatNote: '对话开始（输出为流式），输入 /exit 返回上一页。'
};
const EN = {
  version: 'Version %s',
  osUnsupported: 'Unsupported OS! Requires Windows 10 1703 (build 15063) or higher. Current: %s',
  osLine: 'OS: %s',
  langLine: 'Language: %s (press 4 to switch)',
  hintChoose: 'Enter your choice number: ',
  invalidChoice: 'Invalid choice, try again.',
  pressEnter: 'Press Enter to continue...',
  back: 'Back to previous page',
  ok: 'Done',
  fail: 'Failed',
  goodbye: 'Thanks for using TC-tools. Goodbye!',
  canceled: 'Canceled.',
  homeIntro: 'Welcome to TC-tools - a toolchain installer / checker / lightweight CLI kit for Windows 10 1709+',
  m1: 'Toolchain install toolkit',
  m2: 'Toolchain check & troubleshooting',
  m3: 'Built-in lightweight CLI',
  m4: 'Switch language (Chinese/English)',
  m5: 'Visit our website',
  m6: 'Exit',
  langSwitched: 'Language switched to: %s',
  webOpened: 'Opened https://turtleweb.cc.cd in your default browser',
  p1Title: 'Toolchain install toolkit',
  p1Local: 'Local install (may be older, but fastest)',
  p1Online: 'Online install (newest version, speed depends on network)',
  commentLocal: "Local install uses pre-packaged installers from the packages folder, no internet required.",
  commentOnline: "Online install downloads the newest installer automatically; speed depends on your network.",
  itNode: 'Install Node.js',
  itMingw: 'Install MinGW-w64',
  itGit: 'Install Git for Windows',
  itMsys2: 'Install MSYS2',
  itPnpm: 'Install pnpm',
  itDsh: 'Install Deepseek Harness',
  itDshNpm: 'Install Deepseek Harness (npm -g global)',
  itDshNpx: 'Install Deepseek Harness (npx install & launch)',
  itDshGit: 'Install Deepseek Harness (git + pnpm from source)',
  itC1: 'Install IDE bundle 1 (Bloodshed DEV-C++ 5.11.0 + VS Code)',
  itC2: 'Install IDE bundle 2 (PyCharm + IDLE (Python 3) + Jetbrains Toolbox)',
  itC3: 'Install IDE bundle 3 (CLion + MinGW-w64 13.2 + Jetbrains Toolbox)',
  itC4: 'Install IDE bundle 4 (Qt online installer)',
  itOffice: 'Install office/edu bundle 1 (WPS + QQ + Seewo Whiteboard + DingTalk + WeChat)',
  itAi: 'Install AI bundle 1 (codex + claude code)',
  verLabel: ' (version: %s)',
  instAlready: '%s already installed (%s); skipped to avoid duplicates.',
  instOsBlock: "Pre-install check: current OS is %s, which does not meet Windows 10 1703 (build 15063)+ requirement. Install canceled.",
  instAiBlock: "Your OS is Windows 10 1709 or earlier (build %d); codex/claude code cannot be installed (requires Windows 10 1803+).",
  instLocalMissing: 'Local package not found: %s\nPlease run  packages\fetch-packages.ps1  first to download offline packages, or use [Online install].',
  instDl: 'Downloading: %s',
  instDlBad: 'Download error: server returned an HTML page instead of a file (mirror blocking?). Please download manually with a browser.',
  instRunSilent: 'Installing silently, please wait (click Yes on UAC if asked)...',
  instRunInter: 'Launching interactive installer; when finished, come back here and press Enter.',
  instStart: 'Start installing: %s',
  instOk: 'Install OK! Auto-verification attempted.',
  instFail: 'Install did not succeed (exit code %d).',
  instCancel: 'Installer did not launch or was canceled (UAC denied / code %d).',
  instNodeMissing: "Node.js / npm not found. Please install Node.js first.",
  instGitMissing: "Git not found. Please install Git for Windows first.",
  instPathNote: 'Note: reopen the terminal (this app) after PATH changes to take effect.',
  instVerifyOk: 'Verified OK: %s',
  instVerifyFail: 'Verification failed: %s not found. Check installation or PATH.',
  instOfflinePage: 'Opened official download page in browser: %s',
  instQtNote: 'Note: Qt 6 series (6.2+) officially requires Windows 10 1809+; on Win10 1709 choose Qt 5.15.x.',
  instJbNote: 'Note: JetBrains 2023.2+ officially requires Windows 10 1809+; may not run on 1709. Please be aware.',
  comboDone: 'Bundle install flow finished.',
  installed: 'Installed: %s',
  p2Title: 'Toolchain check & troubleshooting',
  c1: 'Show installed toolchains & versions',
  c2: 'Node.js runtime & dependency check',
  c3: 'Git runtime check',
  c4: 'pnpm runtime check',
  c5: 'MSYS2 runtime check',
  c6: 'Deepseek Harness runtime & dependency check',
  c7: 'Claude Code runtime check',
  c8: 'Codex runtime check',
  c9: 'Microsoft Edge runtime check',
  c10: 'Google Chrome runtime check',
  c11: 'DEV-C++ runtime check',
  c12: 'MinGW-w64 runtime check',
  c13: 'Python runtime check',
  c14: 'IDE runtime check (installed IDEs)',
  c15: 'Office software check',
  c16: 'Back to previous page',
  chkHeader: '--- %s ---',
  chkVer: 'Version: %s',
  chkPath: 'Path: %s',
  chkNotFound: '[X] %s not detected',
  chkOk: '[OK] running normally',
  chkError: '[!] detected but cannot run: %s',
  chkSummaryHead: '===== Installed toolchain summary =====',
  chkSummaryTotal: '%d item(s) total',
  tipNode: 'Tip: use 1-Toolchain toolkit to install Node.js, or download from https://nodejs.org',
  tipGit: 'Tip: install Git via 1-Toolchain toolkit (select [Add to PATH] when installing).',
  tipPnpm: 'Tip: install Node.js first, then run: npm install -g pnpm',
  tipMsys2: 'Tip: install MSYS2 via 1-Toolchain toolkit or from https://www.msys2.org',
  tipDsh: 'Tip: install Deepseek Harness via 1-Toolchain toolkit (online 5A/5B/5C).',
  tipClaude: 'Tip: npm install -g @anthropic-ai/claude-code (needs Node; Windows 10 1803+).',
  tipCodex: 'Tip: npm install -g @openai/codex (needs Node; Windows 10 1803+).',
  tipEdge: 'Tip: Edge ships with Windows 10 1709; use Edge auto-update for newer versions.',
  tipChrome: 'Tip: download from https://www.google.com/chrome/',
  tipDevCpp: 'Tip: install DEV-C++ 5.11.0 via toolkit bundle 1.',
  tipMingw: 'Tip: install MinGW-w64 13.2 via toolkit.',
  tipPython: 'Tip: install Python 3 (with IDLE) via toolkit bundle 2.',
  tipIde: 'Tip: IDE set: VS Code / PyCharm / CLion / JetBrains Toolbox / Qt Creator / DEV-C++.',
  tipOffice: 'Tip: office/edu apps: WPS, QQ, Seewo Whiteboard, DingTalk, WeChat (see bundle 1).',
  p3Title: 'Built-in lightweight CLI',
  p3Desc1: '  - A lightweight conversational AI CLI that runs on Windows 10 1709.',
  p3Desc2: '  - Connect via API Key: pick a vendor (Key only) or customize everything.',
  p3Desc3: '  - Claude Code-like chat style; type /exit to go back.',
  p3Start: 'Launch lightweight CLI',
  cliSelVendor: 'Select model vendor:',
  cliVDeeSeek: 'DeepSeek (API Key only)',
  cliVOpenAI: 'OpenAI',
  cliVMoonshot: 'Moonshot / Kimi',
  cliVGLM: 'Zhipu GLM',
  cliVQwen: 'Alibaba DashScope (compatible mode)',
  cliVSilicon: 'SiliconFlow',
  cliVArk: 'Volcengine Ark',
  cliVOllama: 'Ollama (local, no API Key)',
  cliVCustom: 'Custom (fill in everything)',
  cliKey: 'Enter API Key (Enter to skip if none): ',
  cliUrl: 'Enter Base URL (e.g. https://api.deepseek.com): ',
  cliModel: 'Enter model name (e.g. deepseek-chat): ',
  cliSave: 'Save config for next time (Key stored in plain text at %APPDATA%\\TC-tools\\cli-config.json)? (y/n): ',
  cliSaved: 'Saved.',
  cliLoaded: 'Loaded saved config.',
  cliHelp: 'Commands: /exit back | /clear clear chat | /help help',
  cliPrompt: '> ',
  cliErrNoKey: 'No API Key configured. Restart CLI and pick a vendor / custom.',
  cliErrHttp: 'Request failed: %s',
  cliErrStatus: 'Server returned HTTP %d: %s',
  cliBye: 'Exited CLI, back to previous page.',
  cliChatNote: 'Chat started (streaming). Type /exit to go back.'
};

module.exports = {
  ZH, EN,
  L: class {
    constructor(en) { this.en = !!en; }
    table() { return this.en ? EN : ZH; }
    t(k) { const v = this.table()[k]; return v === undefined ? (EN[k] || ZH[k] || '?') : v; }
    f(k, ...args) {
      let s = this.t(k);
      let i = 0;
      s = s.replace(/%[sd]/g, () => (i < args.length ? String(args[i++]) : ''));
      return s;
    }
  }
};